FROM python:3.12-alpine

WORKDIR /app
RUN apk add --no-cache bash && \
    python -m ensurepip --upgrade && \
    pip install --no-cache-dir --upgrade pip setuptools && \
    rm -rf /root/.cache
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache
COPY . .
SHELL ["/bin/bash", "-c"]
CMD ["python", "-m", "app"]
